### ISSUE TITLE
Feedback on code of conduct

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#284]
I added a short paragraph on conduct within our "community" ;-) to the [Contributing](https://github.com/andybalaam/rabbit-escape/wiki/Contributing-code) page and would appreciate feedback.

If anyone would be prepared to be a secondary contact (in the case where someone does not feel able to contact me about violations) that would be great.  We can obfuscate your email address if you'd prefer, or offer some other way of contacting you.

This might seem like overkill, but I believe making clear what is acceptable is the best way to make people feel welcome and contribute.

**Comment by colonelfazackerley** [comment]
Looks fine.

I don't mind be a secondary contact. Don't really want my email up their, though. Github does not seem to have a contact system in place. 

I guess I could create a (potentially) disposable email address for the purpose.

On a vaguely related note, I was thinking I might do an "intro to git" page, covering the basics of creating a pull request. I was thinking it should be separate from the code contribution page, because we might get someone who just wants to contribute images/animations.

**Comment by andybalaam** [comment]
Thanks. Let's have a think about what contact details we could have for you. Good idea about a git page.

**Comment by andybalaam** [comment]
By the way INSTALL.md is totally badly named and we should reorganise this stuff generally. We want enough in the code so someone can build and run with just a clone of it, but then refer to proper writeups on the wiki.

**Comment by andybalaam** [comment]
@colonelfazackerley if you don't want to provide an email address I think we should just leave it as contact me privately, or log an github issue publicly.  If we grow as a community, we will need to find someone who is happy for an email address to be available.
