### ISSUE TITLE
Speed up button for Android

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#297]
#291 but for Android

**Comment by colonelfazackerley** [comment]
I am working on this. After ~3 hours I managed to install Android studio, compile and get it up on my phone via USB debugging. Speedup does not work, but I feel like I made progress. 
![screenshot_20160125-231029](https://cloud.githubusercontent.com/assets/9596719/12567838/755dbd1a-c3b9-11e5-9f69-ad61dd0130d0.png)

**Comment by colonelfazackerley** [comment]
I made changes that should have the speedup button functional. Did not have time to push it across to my phone to test it.

I noticed that I had inadvertently changed loads in the android studio project files. i will need to see if i can revert that.

**Comment by andybalaam** [comment]
Brilliant that you got it up even though I haven't managed to write anything about Android set up yet.  Sorry it took so long - please do make wiki or other documentation on what you learned, if you can bring yourself.

**Comment by andybalaam** [comment]
> I made changes that should have the speedup button functional. Did not have time to push it across to my phone to test it.

Cool.  I will make a snapshot when I get a chance, and another when this gets in.

**Comment by andybalaam** [comment]
> I noticed that I had inadvertently changed loads in the android studio project files. i will need to see if i can revert that.

Log an issue if you can't figure it out.  I may well have checked too much in to Git - it's only been me working in Android up to now.  In general IDEA makes it pretty tricky to decide what to check in or not check in.  I've tried following a couple of their help pages on it, but they seem out of date or otherwise not suitable.

**Comment by andybalaam** [comment]
Loving the new buttons.

**Comment by colonelfazackerley** [comment]
> please do make wiki or other documentation on what you learned

I dont understand what I am doing enought for that yet.
One tip is to launch android studio from a terminal and grumbly messages about missing dependencies will come up there. You need to hunt down 32 bit versions of them.

I had to put the project file changes back otherwise I cant run through my phone. I think some gitignores are required. not sure on what though.

also uninstall re before starting it in debug mode!

may need to select USB MTP.

speedup works, but I have the button the wrong way round (it glows when they are normal speed).

**Comment by colonelfazackerley** [comment]
this is probably closed by #315
