### ISSUE TITLE
Suggestion: mousePressed only, not full click required.

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#66]
When clicking around frantically, I often do short drag actions instead, which don't drop tokens or switch token mode. I don't think that dragging does anything, so does not need to be reserved for something else. So I played a little after changing it to act directly on mousePressed, rather than a full click. I much preferred it, particularly for harder levels.

```
diff --git a/rabbit-escape-ui-swing/src/rabbitescape/ui/swing/GameUi.java b/rabbit-escape-ui-swing/src/rabbitescape/ui/swing/GameUi.java
index 0402e4d..273014d 100644
--- a/rabbit-escape-ui-swing/src/rabbitescape/ui/swing/GameUi.java
+++ b/rabbit-escape-ui-swing/src/rabbitescape/ui/swing/GameUi.java
@@ -52,14 +52,15 @@ public class GameUi implements StatsChangedListener
         @Override
         public void mousePressed( MouseEvent e )
         {
-            startX  = e.getX();
-            startY  = e.getY();
+            //startX  = e.getX();
+            //startY  = e.getY();
+            click (e.getPoint());
         }
 
         @Override
         public void mouseClicked( MouseEvent e )
         {
-            click( e.getPoint() );
+            //click( e.getPoint() );
         }
 
         @Override

```

**Comment by andybalaam** [comment]
Dragging scrolls. Does this prevent that?

**Comment by colonelfazackerley** [comment]
This would prevent LMB drag scrolling. On win/linux I would always just make the window bigger to obviate scrolling. Are you keen to have LMB drag scrolling for mac users? or to make the desktop version play like the android version? On windows at least I think MMB drag scrolling would be normal.

Perhaps make this a configurable option? I could try and make a pull request for that. In the first instance, maybe just have to edit the config file. If it turns out lots of people want the flexibility a menu can be added to the UI later.

**Comment by andybalaam** [comment]
Internet down at home: will think and comment more when it's back.

**Comment by andybalaam** [comment]
I am keen on LMB scrolling.  I watched 6-10 kids playing on the Raspberry Pi yesterday, and most of them instinctively drag to scroll.  (I also like it myself.)

BTW the kids really liked it, and one was overheard to describe it as "legit" which I believe to be high praise.

Watching the kids also made me see how much of a problem there is with clicks that don't get registered.  I am fairly sure this is because they are recognised as drags.

I'd like to propose 2 features:

1. If there are no scroll bars (because everything is visible) then mousePressed drops a token.

2. If there are scroll bars, but someone does a tiny scroll (note: not a scroll a long way left then right, then let go back where you were) then we drop a token.

Thoughts?

**Comment by colonelfazackerley** [comment]
Sounds like a good remedy. There is a risk that 2. is still slower than dropping a token on a pressed event, because it waits for the corresponding released event. Let's try it.
