### ISSUE TITLE
Ability idea: brolly

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#79]
A rabbit, after picking up a brolly token would walk normally. At the next drop, the rabbit would be able to parachute an unlimited distance without discomfort. It would only last for one drop.

I started inkscaping the token.

**Comment by tttppp** [comment]
I suggest it should last for all future drops, and have the (potentially unwanted) side effect of making them drop slowly.

**Comment by andybalaam** [comment]
Floaters are definitely needed.  I think it would be overkill to have both single-use and multi-use floaters.  So, who can think of good puzzle ideas, and which (single or multi) would make for more interesting puzzles?

**Comment by colonelfazackerley** [comment]
At the moment, there are plenty of levels where a climber goes ahead and digs a barrier out of the way.

I was thinking that this opens the options for a pararabbit to descend first and build a bridge back. It's hard to plan in too much detail without actually making a level and playing with it.

I agree that the parachuting rabbit should drop slowly.

I agree we should only have one type of brolly. I have a preference for single use, but dont mind that much either way.

**Comment by andybalaam** [comment]
I currently have no preference, except for my deep respect for the creators of Lemmings, who went with multi-use.

**Comment by tttppp** [comment]
I prefer multi-use for three fairly minor reasons. 

1. An irreversible change of rabbit state adds potential 'dead ends' to the rabbit game tree. Imagine that you could have some rabbits parachute down, but the end result was not fast enough to save some other rabbits from death by pit. Instead you might be forced to use blockers/diggers to get down from a height, and then can save the other rabbits.

More difficult decisions could be presented if some levels had time limits.

2. Lemmings had reuse, so that's what I'd expect.

3. Brollies are multi-use in real life.

None of these are really clinchers.

An alternative one-shot token might be an abseil rope that allows all future rabbits to safely fall the same cliff.

**Comment by andybalaam** [comment]
Yes, a rope is a nice idea.

**Comment by andybalaam** [comment]
I am trying to avoid the temptation to add loads of abilities.  I think any proposed ability should come with a couple of level ideas that demonstrate it opens up new puzzletunities.

**Comment by tttppp** [comment]
That's a good idea. Maybe they should be added on branches to allow for level development against them. Once there are some good levels that prove the concept then the graphics, sound effects and animations could be finalised to allow it to be merged.

Without the prototype game it might be hard to prove the levels work.

On a related note, a one use brolly could be displayed as a balloon that the rabbit lands on, bursting it. One use brollies would definitely open up some new level ideas.

**Comment by andybalaam** [comment]
Balloon popping is a cool idea, almost tipping me towards single use.

**Comment by colonelfazackerley** [comment]
ref #226 
(which has multi-use umbrellas)

**Comment by andybalaam** [comment]
This is now merged!
